apiVersion: apps/v1beta1          
kind: Deployment                  
metadata:
  name: air-auto-dp                   
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      name: air-rs
      labels:
        db: discogs       
        svc: air-proxy
    spec:
      containers:
        - name: air-container
          image: tommy169/air-proxy:latest
          env:
          - name: AIRTABLE_BASE_KEY
            valueFrom:
              secretKeyRef:
                name: air-secret
                key: base_key
          - name: AIRTABLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: air-secret
                key: api_key           
          ports:
            - name: mycontainer
              containerPort: 80
              protocol: TCP
          volumeMounts:                          
            - name: config                           
              mountPath: /config/base_config.yaml
              subPath: base_config.yaml
          readinessProbe:
            exec:
            command:
              - ls
              - /config/base_config.yaml 
      volumes:                                 
        - name: config
          configMap:
            name: air-config


