base_key: appRZ5mLEQwaJ78Dr
api_key: keyatpSrifzwpWlIv

schema:
    Albums:
     type: object
     properties:
       id:
           description: Unique identifier
           type: string     
       Album: 
           description: Name of Album
           type: string
       Artist:
           description: Name of Artist
           type: string      
       Track:
           description: Array of track
           type: array
           items:
              type: string
       Year:
           description: Year of Album
           type: integer
       Style:
           description: Album's stile tags
           type: array
           items:
             type: string
    Artists:
     type: object
     properties:
       id:
           description: Unique identifier
           type: string
       Artist: 
           description: Name of Artist
           type: string
       Profile:
           description: Artist's profile
           type: string      
       Album:
           description: Array of Albums
           type: array
           items:
              type: string            
    Tracks:
     type: object
     properties:
       id:
           description: Unique identifier
           type: string
       Track: 
           description: Track's name
           type: string
       Album:
           description: Album
           type: string      
       Duration:
           description: Track's duration
           type: integer
                          
          
